// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCLZ_ZdOeBySNFbrilymtXay7kZvq4vuKM',
    appId: '1:1056856930295:web:bcb12656a1a46ad65fa0f2',
    messagingSenderId: '1056856930295',
    projectId: 'iti-final-project-2023',
    authDomain: 'iti-final-project-2023.firebaseapp.com',
    storageBucket: 'iti-final-project-2023.appspot.com',
    measurementId: 'G-HNWXK1N18X',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAIX0Mfr2XunEA3nZ9tDLoQ1xky2f56l4U',
    appId: '1:1056856930295:android:36fec8ce8c27da115fa0f2',
    messagingSenderId: '1056856930295',
    projectId: 'iti-final-project-2023',
    storageBucket: 'iti-final-project-2023.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAlyYglZWJ6ezeyM8J6xgnjJchoDzpMT0k',
    appId: '1:1056856930295:ios:722cbf354a203e3f5fa0f2',
    messagingSenderId: '1056856930295',
    projectId: 'iti-final-project-2023',
    storageBucket: 'iti-final-project-2023.appspot.com',
    iosClientId: '1056856930295-p72kmr7tlsllg7635a5ckuqd74nvh17r.apps.googleusercontent.com',
    iosBundleId: 'com.example.itiFinalProject',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAlyYglZWJ6ezeyM8J6xgnjJchoDzpMT0k',
    appId: '1:1056856930295:ios:e342a4722f32aebd5fa0f2',
    messagingSenderId: '1056856930295',
    projectId: 'iti-final-project-2023',
    storageBucket: 'iti-final-project-2023.appspot.com',
    iosClientId: '1056856930295-q0u64e3q59o1n5k8dd1q37ahj02vagmh.apps.googleusercontent.com',
    iosBundleId: 'com.example.itiFinalProject.RunnerTests',
  );
}
